/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package clash_verge_rev/native */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"



#include <stdlib.h>
#include <android/log.h>

typedef const char* c_string;
typedef long long c_long_long;

#define LOG_TAG "ClashCore-Go"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt32 GoInt;
typedef GoUint32 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_32_bit_pointer_matching_GoInt[sizeof(void*)==32/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// nativeInit 初始化核心
//
extern void nativeInit(c_string homeDir, c_string versionName);

// nativeReset 重置核心状态
//
extern void nativeReset();

// nativeForceGc 强制垃圾回收
//
extern void nativeForceGc();

// nativeStartTun 启动 TUN 设备
//
extern int nativeStartTun(int fd, int mtu);

// nativeStopTun 停止 TUN 设备
//
extern void nativeStopTun();

// nativeLoadConfig 加载配置文件
//
extern int nativeLoadConfig(c_string configPath);

// nativeQueryTraffic 查询流量统计
//
extern c_long_long nativeQueryTraffic();

// nativeGetVersion 获取核心版本
//
extern char* nativeGetVersion();

// freeString 释放 C 字符串内存
//
extern void freeString(char* str);

#ifdef __cplusplus
}
#endif
